main: p1xel.minecraft.bukkit.SpawnPlus
name: SpawnPlus
version: ${project.version}
api-version: 1.13
folia-supported: true
commands:
  spawnplus:
    aliases: [sp, spawnp, splus, spawn]
    description: Main command
permissions:
  spawnplus.reload:
    default: op
    description: Reload configuration
  spawnplus.spawn:
    default: true
    description: Spawn point teleporting command
  spawnplus.help:
    default: true
    description: View help
  spawnplus.set:
    default: op
    description: Set default spawn point
  spawnplus.set.group:
    default: op
    description: Set group spawn point
  spawnplus.set.local:
    default: true
    description: Set user spawn point
  spawnplus.tp:
    default: true
    description: Teleport to default spawn point
  spawnplus.tp.group:
    default: true
    description: Teleport to group spawn point
  spawnplus.tp.local:
    default: true
    description: Teleport to user spawn point


