package p1xel.minecraft.bukkit;

import org.bukkit.plugin.java.JavaPlugin;
import p1xel.minecraft.bukkit.Command.Cmd;
import p1xel.minecraft.bukkit.Command.SpawnCmd;
import p1xel.minecraft.bukkit.Listeners.DeathTP;
import p1xel.minecraft.bukkit.Listeners.LoginTP;
import p1xel.minecraft.bukkit.Storage.Config;
import p1xel.minecraft.bukkit.Storage.Locale;
import p1xel.minecraft.bukkit.Storage.SpawnManager;
import p1xel.minecraft.bukkit.bStats.Metrics;

public class SpawnPlus extends JavaPlugin {

    private static SpawnPlus plugin;
    public static SpawnPlus getInstance() { return plugin;}

    @Override
    public void onLoad() {
        plugin = this;
        saveDefaultConfig();
        Config.config = getConfig();
        new Locale().createFile();
        new SpawnManager().createFile();
    }

    @Override
    public void onEnable() {

        System.out.println(getConfig().getKeys(true));

        getServer().getPluginManager().registerEvents(new DeathTP(), this);
        getServer().getPluginManager().registerEvents(new LoginTP(), this);
        getServer().getPluginCommand("SpawnPlus").setExecutor(new Cmd());
        getServer().getPluginCommand("spawn").setExecutor(new SpawnCmd());

        // Text is generated by https://tools.miku.ac/taag/ (Font: Slant)
        getLogger().info("   _____                            ____  __          ");
        getLogger().info("  / ___/____  ____ __      ______  / __ \\/ /_  _______");
        getLogger().info("  \\__ \\/ __ \\/ __ `/ | /| / / __ \\/ /_/ / / / / / ___/");
        getLogger().info(" ___/ / /_/ / /_/ /| |/ |/ / / / / ____/ / /_/ (__  ) ");
        getLogger().info("/____/ .___/\\__,_/ |__/|__/_/ /_/_/   /_/\\__,_/____/  ");
        getLogger().info("    /_/                                               ");

        int pluginId = 23609;
        new Metrics(this, pluginId);

        getLogger().info("Plugin loaded at v" + getDescription().getVersion());
    }

}
