package p1xel.minecraft.bukkit;

import com.tcoded.folialib.FoliaLib;
import net.milkbowl.vault.economy.Economy;
import org.bukkit.plugin.RegisteredServiceProvider;
import org.bukkit.plugin.java.JavaPlugin;
import p1xel.minecraft.bukkit.Command.Cmd;
import p1xel.minecraft.bukkit.Command.TabList;
import p1xel.minecraft.bukkit.Listeners.DeathTP;
import p1xel.minecraft.bukkit.Listeners.LoginTP;
import p1xel.minecraft.bukkit.Storage.Config;
import p1xel.minecraft.bukkit.Storage.Locale;
import p1xel.minecraft.bukkit.Storage.SpawnManager;
import p1xel.minecraft.bukkit.bStats.Metrics;

public class SpawnPlus extends JavaPlugin {

    private static SpawnPlus plugin;
    public static SpawnPlus getInstance() { return plugin;}
    private static Economy econ = null;
    private static FoliaLib foliaLib;
    public static FoliaLib getFoliaLib() {return foliaLib;}

    @Override
    public void onLoad() {
        plugin = this;
        saveDefaultConfig();
        Config.config = getConfig();
        new Locale().createFile();
        new SpawnManager().createFile();
        foliaLib = new FoliaLib(this);
    }

    @Override
    public void onEnable() {

        Config.checkUpdate();

        getServer().getPluginManager().registerEvents(new DeathTP(), this);
        getServer().getPluginManager().registerEvents(new LoginTP(), this);
        getServer().getPluginCommand("SpawnPlus").setExecutor(new Cmd());
        getServer().getPluginCommand("SpawnPlus").setTabCompleter(new TabList());

        if (setupEconomy()) {
            getLogger().info("Vault function has loaded!");
        } else {
            getLogger().info("Could not find Vault, function has been disabled!");
        }

        updateConfig();

        // Text is generated by https://tools.miku.ac/taag/ (Font: Slant)
        getLogger().info("   _____                            ____  __          ");
        getLogger().info("  / ___/____  ____ __      ______  / __ \\/ /_  _______");
        getLogger().info("  \\__ \\/ __ \\/ __ `/ | /| / / __ \\/ /_/ / / / / / ___/");
        getLogger().info(" ___/ / /_/ / /_/ /| |/ |/ / / / / ____/ / /_/ (__  ) ");
        getLogger().info("/____/ .___/\\__,_/ |__/|__/_/ /_/_/   /_/\\__,_/____/  ");
        getLogger().info("    /_/                                               ");

        int pluginId = 23609;
        new Metrics(this, pluginId);

        getLogger().info("Plugin loaded at v" + getDescription().getVersion());
    }

    public boolean isVaultEnabled() {
        return getServer().getPluginManager().getPlugin("Vault") != null && Config.getBool("hooks.Vault");
    }

    private boolean setupEconomy() {
        if (getServer().getPluginManager().getPlugin("Vault") == null) {
            return false;
        }
        RegisteredServiceProvider<Economy> rsp = getServer().getServicesManager().getRegistration(Economy.class);
        if (rsp == null) {
            return false;
        }
        econ = rsp.getProvider();
        return econ != null;
    }

    public static Economy getEconomy() {
        return econ;
    }

    void updateConfig() {
        if (getConfig().getInt("configuration") < 3) {
            getConfig().set("settings.first-join", true);
            getConfig().set("configuration", 3);
        }

        saveConfig();
    }

}
